workflows:
  ios-native-demo:
    name: iOS Native Demo
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: AgeWallet ASC API Key
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: io.agewallet.sdk.demo.ios
      xcode: latest
    scripts:
      - name: Register test devices
        script: |
          app-store-connect devices register --name "Ash's iPhone" --udid "00008150-001A0DE826B8401C" --ignore-registration-errors
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project example/AgeWalletDemo/AgeWalletDemo.xcodeproj \
            --scheme AgeWalletDemo
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
