workflows:
  ios-native-demo:
    name: iOS Native Demo
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: AgeWallet ASC API Key
    environment:
      groups:
        - ios_signing
      xcode: latest
    scripts:
      - name: Register test devices
        script: |
          app-store-connect devices register --name "Ash's iPhone" --udid "00008150-001A0DE826B8401C" --ignore-registration-errors
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files "io.agewallet.sdk.demo.ios" \
            --type IOS_APP_ADHOC \
            --create \
            --verbose
          keychain initialize
          app-store-connect certificates list \
            --type IOS_DISTRIBUTION \
            --save \
            --verbose
          keychain add-certificates
      - name: Apply code signing to Xcode project
        script: xcode-project use-profiles
      - name: Build IPA
        script: |
          xcodebuild \
            -project example/AgeWalletDemo/AgeWalletDemo.xcodeproj \
            -scheme AgeWalletDemo \
            -archivePath build/ios/xcarchive/AgeWalletDemo.xcarchive \
            -destination 'generic/platform=iOS' \
            archive \
            COMPILER_INDEX_STORE_ENABLE=NO \
            DEVELOPMENT_TEAM=F5T3W2C69Y \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            CODE_SIGN_STYLE=Manual
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
